### ISSUE TITLE
About function now( )

### ISSUE THREAD

**Issue by QQyoyo** [PaulStoffregen/Time#106]
I would like to generate the timestamps for my sensor outputs. 

Then I found now( ) function should return the current time as seconds since Jan 1 1970.

So I include the TimeLib.h and call the now ( ) function. However, the output is not Unix Time Stamps. Just binary numbers starting from 000.

Can anyone help me with this? Thanks!

**Comment by PaulStoffregen** [comment]
This is not the place to ask for help.  Ask on the forums.

Github issues are meant only for reporting defects in the software.
