### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by rapasal** [PaulStoffregen/Time#127]
I cannot find any declaration of licence for this library. The page at [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/) suggests I "ask the maintainers nicely to add a license"... so... 

Please could you add a licence, or clarify that this library is intentionally provided without licence? :)

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/Time/blob/master/Time.cpp#L5

**Comment by rapasal** [comment]
Oops. Looked only in the headers. Thanks!
