### ISSUE TITLE
v1.6.1 contains a breaking change for v1.6.0 clients; Semver suggests v2.0.0 tag.

### ISSUE THREAD

**Issue by terrillmoore** [PaulStoffregen/Time#160]
Thanks for this library.

This is only a documentation bug.

The change from 1.6.0 to 1.6.1 removed Time.h -- this is a breaking change for code that uses Time.h and 1.6.0. In my case, there's an example for the LMIC library that uses this library and this header file. Fortunately, the periodic CI run brought it to attention. I will correct the LMIC examples.

If [Semantic Version](https://semver.org) rules are followed, the version would be v2.0.0. However, I don't know that this is part of the project.

Best regards,
--Terry

**Comment by PaulStoffregen** [comment]
TimeLib.h has been the documented way for years.  This changes has been a long time coming.

Really don't care about semantic version.
