### ISSUE TITLE
millis()

### ISSUE THREAD

**Issue by ThomasDavidDev** [PaulStoffregen/Time#17]
Hi, 

On the official reference I read this: (http://www.arduino.cc/en/Reference/Millis)

>###### "millis() - Returns the number of milliseconds since the Arduino board began running the current program. This number will overflow (go back to zero), after approximately 50 days."

My question: How will the system react to this overflow? Is there a forced re-sync of the time? It's very important for my project because it should guarantee a greater function time.

Thanks in advance!

**Comment by PaulStoffregen** [comment]
This is not the place for usage questions.  Ask on the Arduino forum.

Please, only post here for confirmed bug or problems in the library.
