### ISSUE TITLE
relentless use of int - are they strictly required?

### ISSUE THREAD

**Issue by matteliot** [PaulStoffregen/Time#20]
There seems to be a bunch of places where int just isn't necessary, ie- hour(), especially:
int     hourFormat12();    // the hour now in 12 hour format

Any reason not to use uint_8 in that case? My project's so hard up for space and this could be worthwhile for me to change and I'm looking for some insight as to why int is so frequently the go-to.

Am I missing the reason they're a full int?

**Comment by michaelmargolis** [comment]
When I created the first version of this library, I did use 8 bit data types - see: http://playground.arduino.cc/Code/DateTime

But David Mellis from the Arduino team requested I change these to int to bring the API closer to that used for Processing time functions.  At the time, he was considering including this library in the Arduino core. Alas, that did no happen but the updated library, renamed time, use that API suggested by Mellis

There should be no problem changing the types back to bytes (uint8_t) if you want to save a little space.
