### ISSUE TITLE
given a time_t object, how do i get ascii of day month year hour from it but NOT set the system clock

### ISSUE THREAD

**Issue by gtessler24** [PaulStoffregen/Time#29]
e.g 

time_t foo

foo.month()
foo.hour ()

etc

thank you.

**Comment by PaulStoffregen** [comment]
this issue tracker is *not* the proper place to ask for support

**Comment by gtessler24** [comment]
where do we get support?  Thank you.

**Comment by PaulStoffregen** [comment]
https://forum.arduino.cc/
