### ISSUE TITLE
Timekeeping in powerdown mode

### ISSUE THREAD

**Issue by shirish47** [PaulStoffregen/Time#34]
I am using this library with time library (https://github.com/rocketscream/Low-Power)
I make my code to sleep in powerdown for say 8 seconds and then check the time and its not exact.
timer0 is shutdown. Is it possible to keep timer0 on so the timekeeping is possible for TimeLib ?

**Comment by PaulStoffregen** [comment]
No.  AVR timer0 always stops when the chip is in powerdown mode.

**Comment by PaulStoffregen** [comment]
You need a RTC chip, network communication to a NTP server, GPS data, or other sync provider to set the time accurately.

**Comment by shirish47** [comment]
ok,

Thanks That mean would have to make RTC external to AVR ..anyways thanks..
