### ISSUE TITLE
Compile errors in Arduino 1.6.10 and 1.6.11

### ISSUE THREAD

**Issue by guenego** [PaulStoffregen/Time#53]
error is 
'tmElements_t' was not declared in this scope

it run good with 1.6.9

**Comment by mjbcopland** [comment]
Arduino 1.6.10 updated the toolchain to version 3.5.3 which uses avr-libc 2.0.0 which now has a `time.h`.  On Mac and Windows, the compiler will include this `time.h` instead of the `Time.h` from the Time library. You will need to include `TimeLib.h` instead.

**Comment by mans20** [comment]
Mans
