### ISSUE TITLE
Possible PIBKAC. Can't locate Time.h in arduino IDE.

### ISSUE THREAD

**Issue by ebeyer** [PaulStoffregen/Time#55]
I've run the TeensyduinoInstall.linux64 a couple of times and am told that I have installed all files for the Time library but I am unable to locate the Time library in either the arduino IDE or in my file manager.  Consequently, my sketch fails to compile.  Where are the supposedly installed files being put and, more importantly, how do I get the arduino IDE to use them?

Many humble thanks in advance for your help.
EB

**Comment by PaulStoffregen** [comment]
First select Teensy in Tools > Boards (because the examples menu updates depending on your board).  Then open any example, from File > Examples > Time.

**Comment by ebeyer** [comment]
Thanks!
