### ISSUE TITLE
SECS_PER_YEAR is incorrect.

### ISSUE THREAD

**Issue by gsexton** [PaulStoffregen/Time#66]
The definition of SECS_PER_YEAR is

52*SECS_PER_WEEK

That's not right, because no day in the Gregorian calendar has 364 days.

To really do it correctly, you need a function that is

365UL*SECS_PER_DAY+(isLeap(year) ? SECS_PER_DAY : 0);

**Comment by Bewear** [comment]
I've noticed that every 30 minutes my Arduino loses one second with this library, maybe this is why it happens?
I'm writing this if someone needs:
bool isLeap (int year) {
   if((year%4 and !year%100) or year%400) return true;
   return false;
}

**Comment by PaulStoffregen** [comment]
https://github.com/PaulStoffregen/Time/commit/6dd00e286741bdcc061c305eba0e1294fe171a6d
