### ISSUE TITLE
Weekday fails on October 31... why?

### ISSUE THREAD

**Issue by aprada66** [PaulStoffregen/Time#83]
I have a simple clock: Arduino + LCD + RTC chip.

Date and Time are printed every second, but I note that the day of the week fails on October 31

In my circuit:
October 30/2017 = Monday
**October 31/2017 = Saturday  ??????????????**
November 1/2017 = Wednesday

Please check.

Regards,

APR

**Comment by PaulStoffregen** [comment]
I tried to investigate this problem, but could not reproduce it.  Because you did not provide a program to test, I had to make one.  Here's why I tried.

    #include <TimeLib.h>

    const char *days[] = {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"};

    void setup() {
      Serial.begin(9600);
      while (!Serial) ; // wait
  
      setTime(23, 59, 55, 30, 10, 2017);
      for (int i=0; i < 10; i++) {
        digitalClockDisplay();
        delay(1000);
      }
      Serial.println();
  
      setTime(23, 59, 55, 31, 10, 2017);
      for (int i=0; i < 10; i++) {
        digitalClockDisplay();
        delay(1000);
      }
      Serial.println();
    }

    void loop() {
    }

    void digitalClockDisplay(){
      // digital clock display of the time
      Serial.print(hour());
      printDigits(minute());
      printDigits(second());
      Serial.print(" ");
      Serial.print(day());
      Serial.print(" ");
      Serial.print(month());
      Serial.print(" ");
      Serial.print(year());
      Serial.print("   ");
      Serial.print(days[weekday()-1]);
      Serial.println();
    }

    void printDigits(int digits) {
      // utility function for digital clock display: prints preceding colon and leading 0
      Serial.print(":");
      if(digits < 10)
        Serial.print('0');
      Serial.print(digits);
    }

When I run this, I get this result in the serial monitor:

    23:59:55 30 10 2017   Monday
    23:59:56 30 10 2017   Monday
    23:59:57 30 10 2017   Monday
    23:59:58 30 10 2017   Monday
    23:59:59 30 10 2017   Monday
    0:00:00 31 10 2017   Tuesday
    0:00:01 31 10 2017   Tuesday
    0:00:02 31 10 2017   Tuesday
    0:00:03 31 10 2017   Tuesday
    0:00:04 31 10 2017   Tuesday

    23:59:55 31 10 2017   Tuesday
    23:59:56 31 10 2017   Tuesday
    23:59:57 31 10 2017   Tuesday
    23:59:58 31 10 2017   Tuesday
    23:59:59 31 10 2017   Tuesday
    0:00:00 1 11 2017   Wednesday
    0:00:01 1 11 2017   Wednesday
    0:00:02 1 11 2017   Wednesday
    0:00:03 1 11 2017   Wednesday
    0:00:04 1 11 2017   Wednesday
