### ISSUE TITLE
Compiles, but does not run on ESP32

### ISSUE THREAD

**Issue by JimPos** [PaulStoffregen/Time#84]
In the example for ESP8266
Changed ESP8266Wifi.h to WiFi.h
and commented out 
Serial.println(Udp.localPort());

Compiles without error but doesn't run when uploaded to an ESP32

**Comment by PaulStoffregen** [comment]
I do not directly support ESP8266.  I depend on people from the ESP community to resolve ESP-specific problems.

**Comment by JimPos** [comment]
Sorry, I was wrong.
It works fine for ESP32.
My serial port was configured wrong.
Closing the issue
