### ISSUE TITLE
Modify makeTime to take the argument as a const reference

### ISSUE THREAD

**Issue by GiovanniCmpaner** [PaulStoffregen/Time#85]
Change from
`time_t makeTime(tmElements_t &tm);  // convert time elements into time_t`
to
`time_t makeTime(const tmElements_t &tm);  // convert time elements into time_t`

So it can be called using initializer list, like this:
`return makeTime({ 0, 0, myTime.hour, 0, myTime.day, myTime.month, myTime.year - 1970 })`
Rather than:
`tmElements_t tm;`
`tm.Second = 0;`
`tm.Minute = 0;`
`tm.Hour = myTime.hour;`
`tm.Day = myTime.day;`
`tm.Month = myTime.month;`
`tm.Year = myTime.year - 1970;`
`return makeTime(tm);`
This example is often used when using input with separated fields or when converting from strings, specially in filters.
And as in the function body tm isn't modified, it would describe the function behavior in a better way.

**Comment by PaulStoffregen** [comment]
done
